steps:
- name: gradle:7.5.1-focal
  entrypoint: bash
  args:
  - -c
  - |
    set -e
    export PROJECT_VERSION=$(date -u '+%y-%m-%d--%H-%M')
    printenv
    ./gradlew \
      clean
    ./gradlew \
      spring-boot-app:jib
  env: ['GRADLE_USER_HOME=/workspace/.gradle', 'REGION=${_REGION}', 'PROJECT_ID=${_PROJECT_ID}']

# images: ["${_REGION}-docker.pkg.dev/${_PROJECT_ID}/docker/spring-boot-app"]
options:
  logging: CLOUD_LOGGING_ONLY
