apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app
  namespace: default
spec:
  selector:
    app: spring-boot-app
  ports:
  - name: http
    port: 8080
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      terminationGracePeriodSeconds: 20
      containers:
      - name: spring-boot-app
        image: us-central1-docker.pkg.dev/ylebi-rnd/docker/spring-boot-app:ylebi_DEV_22.11.25-11.52
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: API_NAME
          value: spring-boot-app
        - name: JAVA_OPTS
          value: -Xms512m -Xmx512m
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 5
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 5
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
