apiVersion: v1
kind: Service
metadata:
  name: undertow-demo-app
  namespace: default
spec:
  selector:
    app: undertow-demo-app
  ports:
  - name: http
    port: 8083
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: undertow-demo-app
  namespace: default
  annotations:
    moniker.spinnaker.io/stack: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: undertow-demo-app
  template:
    metadata:
      labels:
        app: undertow-demo-app
    spec:
      terminationGracePeriodSeconds: 20
      containers:
      - name: undertow-demo-app
        image: us-central1-docker.pkg.dev/ylebi-rnd/docker/undertow-demo-app:ealebed_DEV_22.05.18-15.03
        ports:
        - name: http
          containerPort: 8083
        env:
        - name: API_NAME
          value: undertow-demo-app
        - name: JAVA_OPTS
          value: -Xms512m -Xmx512m -Dconfig.file=conf/prod.conf
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/live
          failureThreshold: 5
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/ready
          failureThreshold: 5
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
